MODULE Writing_Outputs
  !________________________________________________________________________________________!

  USE Parametrization
  USE ncio, only: nc_create, nc_write_attr, nc_write_dim
  USE Support_functions, only: config_file_access
  
  IMPLICIT NONE

  !Declaring local variables
  INTEGER, PRIVATE :: i

CONTAINS

  !________________________________________________________________________________________!
  !Subroutine generating a new empty netCDF file with high-resolution grid 
  !________________________________________________________________________________________!
  
  SUBROUTINE downscaled_outputs_grid_init(x_ds_grid,y_ds_grid, config_namelist_blockname,ios, fu)

    IMPLICIT NONE
    
    DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: x_ds_grid(:), y_ds_grid(:)
    CHARACTER(LEN=100), INTENT(OUT) :: config_namelist_blockname
    INTEGER, INTENT(INOUT):: ios, fu 

    !______________________________________________________________________________________!
    !Reading outputs variables in the configuration file
    !______________________________________________________________________________________!
    config_namelist_blockname="Downscaled_outputs"
    
    CALL config_file_access(ios, fu)

    !______________________________________________________________________________________!
    ALLOCATE (x_ds_grid(921))
    ALLOCATE (y_ds_grid(521))

    x_ds_grid(:)=0
    y_ds_grid(:)=0

    
    x_ds_grid(1)=-443750.d0 
    DO i=2,xdim_ds_grid
       x_ds_grid(i)=x_ds_grid(i-1)+1000.d0
    ENDDO

    y_ds_grid(1)=-251600.d0
    DO i=2,ydim_ds_grid
       y_ds_grid(i)=y_ds_grid(i-1)+1000.d0
    ENDDO
  
       
    CALL nc_create(downscaled_climate_data_file, OVERWRITE=.TRUE.,NETCDF4=.TRUE.)

    CALL nc_write_attr(downscaled_climate_data_file,"Title","High-resolution climate data grid")
    CALL nc_write_attr(downscaled_climate_data_file,"Institution", &
                       "Laboratoire de Sciences du Climat et de l'Environnement, GeoDS project")

    CALL nc_write_dim(downscaled_climate_data_file,"x",x=x_ds_grid,units="m")
    CALL nc_write_dim(downscaled_climate_data_file,"y",x=y_ds_grid,units="m")
    call nc_write_dim(downscaled_climate_data_file,"time",x=1.0, &
         units="years",calendar="360_day", unlimited=.TRUE.)
    
  END SUBROUTINE downscaled_outputs_grid_init

  !________________________________________________________________________________________!
  !Subroutine writing downscaled climate data in the netCDF file generated by the downscaled_outputs_grid_init subroutine
  !________________________________________________________________________________________!
  

END MODULE Writing_Outputs
